# Generated by Django 5.0.6 on 2024-05-19 01:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("codebuddy_app_baackend", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collaborationsession",
            name="created_by",
            field=models.CharField(max_length=100),
        ),
        migrations.RemoveField(
            model_name="collaborationsession",
            name="participants",
        ),
        migrations.AddField(
            model_name="collaborationsession",
            name="participants",
            field=models.JSONField(default=list),
        ),
    ]
